version: '3.1'

services:

  pg-docker:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db:/data/db
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=todolist
